/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 coffee.gltf --transform
Author: Petru Grati (https://sketchfab.com/einmeister5)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/create-coffee-machine-3f0ef2ca98ff40868eed78a45b2cf857
Title: Create Coffee Machine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Coffee(props) {
  const { nodes, materials } = useGLTF('/coffee-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 0, -5.95]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Create_coffee_machine_very_original_Red001_0.geometry} material={materials['Red.001']} />
          <mesh geometry={nodes.Create_coffee_machine_very_original_Red_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Create_coffee_machine_very_original_Metal_0.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Create_coffee_machine_very_original_Red002_0.geometry} material={materials['Red.002']} />
          <mesh geometry={nodes.Create_coffee_machine_very_original_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes.Create_coffee_machine_very_original_Transparent_0.geometry} material={materials.Transparent} />
          <mesh geometry={nodes.Create_coffee_machine_very_original_Black_plastic_0.geometry} material={materials.Black_plastic} />
        </group>
        <group position={[0, 0, -5.95]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.WaterBucket_Transparent_0.geometry} material={materials.Transparent} />
          <mesh geometry={nodes.WaterBucket_Red_0.geometry} material={materials.material} />
        </group>
        <group position={[0, 0, -5.95]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Handle_Metal_0.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Handle_Black_plastic_0.geometry} material={materials.Black_plastic} />
        </group>
        <group position={[0, 0, -5.95]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Bottom_Part_Metal_0.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Bottom_Part_Red_0.geometry} material={materials.material} />
        </group>
        <group position={[0, 0, -5.95]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Attachments_Metal_0.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Attachments_Metal_0_1.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Attachments_Metal_0_2.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Attachments_Metal_0_3.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Attachments_Black_plastic_0.geometry} material={materials.Black_plastic} />
          <mesh geometry={nodes.Attachments_Black_plastic_0_1.geometry} material={materials.Black_plastic} />
        </group>
        <mesh geometry={nodes.Removable_Transparent_0.geometry} material={materials.Transparent} position={[0, 0, -5.95]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/coffee-transformed.glb')
