/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 lil_robort.gltf --transform
Author: Diego G. (https://sketchfab.com/empty_mirror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-robot-arbeit-001-ecff33b6a5944f46aec468ab054c15d1
Title: Little Robot - Arbeit 001
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LilRobort(props) {
  const { nodes, materials } = useGLTF('/lil_robort-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.39, 0.5]}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.Robot_2} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Robot} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Robot_Pies} />
      </group>
      <group position={[0, 0, 0.5]}>
        <mesh geometry={nodes.Object_18.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Metal_2} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Metal} />
      </group>
      <group position={[0.51, 0.85, 1.01]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials.Cristal} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.LuzFoco} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Robot_2} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Cara} position={[0.3, 0.31, 0.92]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Robot} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Robot_2} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Pantalla} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.BotonRojo} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Robot_2} position={[0, -0.4, 0.5]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Texto} position={[0.04, -1.05, 1]} rotation={[Math.PI / 2, 0, 0]} scale={0.16} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Metal} position={[0, 0, 1]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Texto} position={[0.36, 0.82, -0.01]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.16} />
    </group>
  )
}

useGLTF.preload('/lil_robort-transformed.glb')
